dotnet: 3.0.100
mono: none
language: csharp
solution: Algorist.EventSourcing.sln
script:
  - dotnet restore
  - dotnet test
  - dotnet clean
  - dotnet build -c Release
  - dotnet pack -c Release
  - dotnet nuget push **/*.nupkg -k $NUGET_API_KEY -s https://api.nuget.org/v3/index.json 
