addons:
  snaps:
    - name: dotnet-sdk
      classic: true
      channel: latest
sudo: required
mono: none
language: csharp
solution: Algorist.EventSourcing.sln
script:
  - sudo snap alias dotnet-sdk.dotnet dotnet
  - dotnet restore
  - dotnet test
  - dotnet clean
  - dotnet build -c Release
  - dotnet pack -c Release
deploy:
  skip_cleanup: true
  provider: script
  script: dotnet nuget push **/*.nupkg -k $NUGET_API_KEY -s https://api.nuget.org/v3/index.json
  on:
    branch: master